apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    database: db0
    user: admin
    password: admin
    url: http://influxdb:8086
    isDefault: false
    editable: true
    
  - name: Prometheus
    type: prometheus
    access: proxy            
    url: http://prometheus:9090
    isDefault: true
    editable: true    